//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Commande()
        {
            this.ligne_Commande = new HashSet<ligne_Commande>();
        }
    
        public int code_cde { get; set; }
        public Nullable<System.DateTime> date_commande { get; set; }
        public string Total_HT { get; set; }
        public string TVA { get; set; }
        public string Total_TTC { get; set; }
        public Nullable<int> ID_F { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ligne_Commande> ligne_Commande { get; set; }
        public virtual Fournisseur Fournisseur { get; set; }
    }
}
