//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vente()
        {
            this.Ligne_Vente = new HashSet<Ligne_Vente>();
        }
    
        public int Code_Vente { get; set; }
        public int CodeClt { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string Remarque { get; set; }
        public string TOTAL_HT { get; set; }
        public string TVA { get; set; }
        public string TOTAL_TTC { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ligne_Vente> Ligne_Vente { get; set; }
    }
}
