//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produit()
        {
            this.Ligne_Commande = new HashSet<Ligne_Commande>();
        }
    
        public int code_Produit { get; set; }
        public string Nom_Produit { get; set; }
        public Nullable<int> Quantité_Produit { get; set; }
        public Nullable<int> Prix_Produit { get; set; }
        public Nullable<int> codecateg { get; set; }
    
        public virtual Catégorie Catégorie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ligne_Commande> Ligne_Commande { get; set; }
    }
}
